// "use strict";
exports.__esModule = true;
exports.getAllCommandsTypes =
  exports.addProductInCommandTypes =
  exports.createProductInCommandTypes =
  exports.createCommandTypes =
    void 0;
exports.createCommandTypes = {
  SET_CREATE_COMMAND: "COMMAND/SET_CREATE_COMMAND",
  SET_CREATE_COMMAND_LOADING: "COMMAND/SET_CREATE_COMMAND_LOADING",
  SET_CREATE_COMMAND_ERROR: "COMMAND/SET_CREATE_COMMAND_ERROR",
};
exports.createProductInCommandTypes = {
  SET_CREATE_PRODUCT_IN_COMMAND: "COMMAND/SET_CREATE_PRODUCT_IN_COMMAND",
  SET_CREATE_PRODUCT_IN_COMMAND_LOADING:
    "COMMAND/SET_CREATE_PRODUCT_IN_COMMAND_LOADING",
  SET_CREATE_PRODUCT_IN_COMMAND_ERROR:
    "COMMAND/SET_CREATE_PRODUCT_IN_COMMAND_ERROR",
};
exports.addProductInCommandTypes = {
  SET_ADD_PRODUCT_IN_COMMAND: "COMMAND/SET_ADD_PRODUCT_IN_COMMAND",
  SET_ADD_PRODUCT_IN_COMMAND_LOADING:
    "COMMAND/SET_ADD_PRODUCT_IN_COMMAND_LOADING",
  SET_ADD_PRODUCT_IN_COMMAND_ERROR: "COMMAND/SET_ADD_PRODUCT_IN_COMMAND_ERROR",
};
exports.getAllCommandsTypes = {
  SET_GET_ALL_COMMANDS: "COMMAND/SET_GET_ALL_COMMANDS_",
  SET_GET_ALL_COMMANDS_LOADING: "COMMAND/SET_GET_ALL_COMMANDS_LOADING",
  SET_GET_ALL_COMMANDS_ERROR: "COMMAND/SET_GET_ALL_COMMANDS_ERROR",
};
