// "use strict";
exports.__esModule = true;
exports.loginUserTypes =
  exports.getInfoClientTypes =
  exports.getAllClientsTypes =
    void 0;
exports.getAllClientsTypes = {
  SET_GET_ALL_CLIENTS: "USER/SET_GET_ALL_CLIENTS",
  SET_GET_ALL_CLIENTS_LOADING: "USER/SET_GET_ALL_CLIENTS_LOADING",
  SET_GET_ALL_CLIENTS_ERROR: "USER/SET_GET_ALL_CLIENTS_ERROR",
};
exports.getInfoClientTypes = {
  SET_GET_INFO_CLIENT: "USER/SET_GET_INFO_CLIENT",
  SET_GET_INFO_CLIENT_LOADING: "USER/SET_GET_INFO_CLIENT_LOADING",
  SET_GET_INFO_CLIENT_ERROR: "USER/SET_GET_INFO_CLIENT_ERROR",
};
exports.loginUserTypes = {
  SET_LOGIN_USER: "USER/SET_LOGIN_USER",
  SET_LOGIN_USER_LOADING: "USER/SET_LOGIN_USER_LOADING",
  SET_LOGIN_USER_ERROR: "USER/SET_LOGIN_USER_ERROR",
};
